### ISSUE TITLE
Error: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by dvitry** [PedroGuerraPT/vscode-atv#1]
Hi, I installed this extension and at first it seemed to work well.  Now in my build.xml files I constantly get an error message at the top of the screen that says: "Cannot read property 'path' of undefined".

![image](https://user-images.githubusercontent.com/10070097/36187528-cf980e74-113d-11e8-9d22-7a0675e4f469.png)

**Comment by ghost** [comment]
El gringo esta escena estaba funcionando bien pero después empezó a marar. ¿Consiga esto por favor bien?

**Comment by JoshAntiRute** [comment]
Hey amigo, esta advertencia es muy aburrido, puedes hacer la actualización de eso por favor? muchas gracias. Te doy una donación para eso! (quizás)

**Comment by ghost** [comment]
Gringo estoy aguardando tu respuesta con la máxima urgencia.

**Comment by PedroGuerraPT** [comment]
Hey everyone,

I'm aware of this issue but I cannot estimate when I will be able to solve it. If anyone manages to find a solution, please feel free to submit a pull request.

**Comment by JoshAntiRute** [comment]
ya no vale la pena pedir ayuda a las personas con el nombre Leandro! 😝

**Comment by JoshAntiRute** [comment]
¡Ya trabaja, muchas gracias!

**Comment by ghost** [comment]
Arriba arriba. Ya funciona. Muy bien muchacho

**Comment by ghost** [comment]
Olé

**Comment by PedroGuerraPT** [comment]
@dvitry The issue was with VSCode itself. Please update to version 1.20.1 to solve it.

**Comment by dvitry** [comment]
Gracias!  I will upgrade.
