### ISSUE TITLE
Ant target execution: is this supported? How to execute it?

### ISSUE THREAD

**Issue by Patlatus** [PedroGuerraPT/vscode-atv#3]
Does this extension allow to execute ant target? Is this designed only to view ant file without ability to execute it?
If there is an option to execute Ant script from this extension, how do I do that?

**Comment by PedroGuerraPT** [comment]
@Patlatus The extension was designed for jumping easily between targets, so unfortunately it cannot execute ant files. There is however another extension on the marketplace, which I think that allows it.

**Comment by Patlatus** [comment]
what is the name of that extension?

**Comment by PedroGuerraPT** [comment]
[Ant Target Runner](https://marketplace.visualstudio.com/items?itemName=nickheap.vscode-ant)

**Comment by Patlatus** [comment]
Thanks @PedroGuerraPT , I will try it. Thanks you very much for your help and quick response, I really appreciate this.
